# Generated by Django 3.1.4 on 2020-12-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs_api', '0006_auto_20201228_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidates',
            name='apply_for',
            field=models.ManyToManyField(related_name='Jobs', to='jobs_api.Jobs'),
        ),
    ]
